version: '3'

services:
  client:
    build:
      context: ./client
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
  server:
    build: ./server
    ports:
      - "8800:8800"
    env_file: 
      - ./server/.env
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge

